2021-10-19 17:08:25,640 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:08:26,136 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:08:26,144 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:08:26,180 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:08:26,180 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:12:04,503 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:12:05,030 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:12:05,039 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:12:05,075 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:12:05,076 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:12:16,388 ERROR response_service.py:51 __status:500__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": 500, "message": "\u670d\u52a1\u5f02\u5e38:'NoneType' object has no attribute 'token'", "data": null}
2021-10-19 17:12:16,400 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:12:16] "[35m[1mPOST /testservice/login HTTP/1.1[0m" 500 -
2021-10-19 17:12:57,571 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:12:57,630 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:12:58,157 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:12:58,165 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:12:58,201 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:12:58,201 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:13:00,072 ERROR response_service.py:51 __status:500__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": 500, "message": "\u670d\u52a1\u5f02\u5e38:'str' object has no attribute 'get'", "data": null}
2021-10-19 17:13:00,085 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:13:00] "[35m[1mPOST /testservice/login HTTP/1.1[0m" 500 -
2021-10-19 17:13:23,944 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:13:24,003 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:13:24,501 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:13:24,511 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:13:24,546 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:13:24,547 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:14:44,817 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:14:44,899 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:14:45,401 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:14:45,409 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:14:45,444 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:14:45,444 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:14:50,018 ERROR response_service.py:51 __status:500__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": 500, "message": "\u670d\u52a1\u5f02\u5e38:'str' object has no attribute 'get'", "data": null}
2021-10-19 17:14:50,031 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:14:50] "[35m[1mPOST /testservice/login HTTP/1.1[0m" 500 -
2021-10-19 17:15:17,690 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:15:18,912 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:15:18,921 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:15:19,156 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:15:19,156 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:15:54,292 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:15:55,487 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:15:55,496 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:15:55,591 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:15:55,592 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:16:37,787 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:16:39,034 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:16:39,043 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:16:39,141 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:16:39,141 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:16:45,258 ERROR response_service.py:51 __status:500__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": 500, "message": "\u670d\u52a1\u5f02\u5e38:tuple index out of range", "data": null}
2021-10-19 17:16:45,271 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:16:45] "[35m[1mPOST /testservice/login HTTP/1.1[0m" 500 -
2021-10-19 17:17:15,658 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:17:15,735 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:17:16,884 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:17:16,893 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:17:16,985 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:17:16,985 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:17:19,228 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:17:19,724 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:17:19,732 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:17:19,768 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:17:19,769 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:17:22,352 ERROR response_service.py:51 __status:500__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": 500, "message": "\u670d\u52a1\u5f02\u5e38:tuple index out of range", "data": null}
2021-10-19 17:17:22,368 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:17:22] "[35m[1mPOST /testservice/login HTTP/1.1[0m" 500 -
2021-10-19 17:18:03,907 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:18:05,162 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:18:05,171 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:18:05,272 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:18:05,273 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:18:40,829 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:18:41,987 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:18:41,996 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:18:42,089 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:18:42,090 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:19:06,962 ERROR LoginLogDBS.py:36 LoginLogDBS:(pymysql.err.IntegrityError) (1048, "Column 'phone' cannot be null")
[SQL: INSERT INTO login_log (create_time, update_time, id, phone, token) VALUES (%(create_time)s, %(update_time)s, %(id)s, %(phone)s, %(token)s)]
[parameters: {'create_time': datetime.datetime(2021, 10, 19, 17, 19, 6, 944913), 'update_time': datetime.datetime(2021, 10, 19, 17, 19, 6, 944913), 'id': 1450391045819998208, 'phone': None, 'token': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2021-10-19 17:19:07,472 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u5931\u6548\u91cd\u65b0\u751f\u6210!", "data": {"token": "\u8bf7\u6c42\u5931\u8d25:\u77ed\u4fe1\u9a8c\u8bc1\u7801\u9519\u8bef"}}
2021-10-19 17:19:09,719 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:19:09] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:20:00,425 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:20:00,925 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:20:00,933 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:20:00,971 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:20:00,972 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:20:05,873 ERROR LoginLogDBS.py:36 LoginLogDBS:(pymysql.err.IntegrityError) (1048, "Column 'phone' cannot be null")
[SQL: INSERT INTO login_log (create_time, update_time, id, phone, token) VALUES (%(create_time)s, %(update_time)s, %(id)s, %(phone)s, %(token)s)]
[parameters: {'create_time': datetime.datetime(2021, 10, 19, 17, 20, 5, 862664), 'update_time': datetime.datetime(2021, 10, 19, 17, 20, 5, 862664), 'id': 1450391292944195584, 'phone': None, 'token': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2021-10-19 17:20:05,879 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u5931\u6548\u91cd\u65b0\u751f\u6210!", "data": {"token": "\u8bf7\u6c42\u5931\u8d25:\u77ed\u4fe1\u9a8c\u8bc1\u7801\u9519\u8bef"}}
2021-10-19 17:20:05,879 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:20:05] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:21:18,148 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:21:18,204 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:21:18,688 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:21:18,696 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:21:18,731 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:21:18,731 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:21:20,748 WARNING response_service.py:54 __status:403__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u5931\u8d25,\u8bf7\u6c42\u5931\u8d25:\u77ed\u4fe1\u9a8c\u8bc1\u7801\u9519\u8bef!", "data": null}
2021-10-19 17:21:20,763 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:21:20] "[31m[1mPOST /testservice/login HTTP/1.1[0m" 403 -
2021-10-19 17:21:33,153 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:21:33,220 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:21:33,713 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:21:33,721 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:21:33,758 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:21:33,759 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:21:34,835 WARNING response_service.py:54 __status:403__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": 403, "message": "\u5931\u8d25,\u8bf7\u6c42\u5931\u8d25:\u77ed\u4fe1\u9a8c\u8bc1\u7801\u9519\u8bef!", "data": null}
2021-10-19 17:21:34,849 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:21:34] "[31m[1mPOST /testservice/login HTTP/1.1[0m" 403 -
2021-10-19 17:21:54,585 WARNING response_service.py:54 __status:403__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": 403, "message": "\u5931\u8d25,61tmqa0ho0i3j20k4vv6q3jt37a1gmt3ju!", "data": null}
2021-10-19 17:21:54,598 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:21:54] "[31m[1mPOST /testservice/login HTTP/1.1[0m" 403 -
2021-10-19 17:22:08,738 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:22:08,797 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:22:09,318 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:22:09,327 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:22:09,363 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:22:09,363 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:22:10,808 ERROR LoginLogDBS.py:36 LoginLogDBS:(pymysql.err.IntegrityError) (1048, "Column 'phone' cannot be null")
[SQL: INSERT INTO login_log (create_time, update_time, id, phone, token) VALUES (%(create_time)s, %(update_time)s, %(id)s, %(phone)s, %(token)s)]
[parameters: {'create_time': datetime.datetime(2021, 10, 19, 17, 22, 10, 793441), 'update_time': datetime.datetime(2021, 10, 19, 17, 22, 10, 793441), 'id': 1450391816938594304, 'phone': None, 'token': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2021-10-19 17:22:10,815 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u5931\u6548\u91cd\u65b0\u751f\u6210!", "data": {"token": "uf6qet8gujvbv2prpod6ap08ecs1gmt3ke"}}
2021-10-19 17:22:10,815 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:22:10] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:22:45,386 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:22:45,450 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:22:45,950 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:22:45,957 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:22:45,992 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:22:45,993 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:23:38,437 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\services\\LoginLogDBS.py', reloading
2021-10-19 17:23:38,489 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:23:38,994 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:23:39,001 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:23:39,037 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:23:39,038 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:23:41,612 ERROR LoginLogDBS.py:38 LoginLogDBS:(pymysql.err.IntegrityError) (1048, "Column 'phone' cannot be null")
[SQL: INSERT INTO login_log (create_time, update_time, id, phone, token) VALUES (%(create_time)s, %(update_time)s, %(id)s, %(phone)s, %(token)s)]
[parameters: {'create_time': datetime.datetime(2021, 10, 19, 17, 23, 41, 599470), 'update_time': datetime.datetime(2021, 10, 19, 17, 23, 41, 599470), 'id': 1450392197806563328, 'phone': None, 'token': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2021-10-19 17:23:41,619 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u5931\u6548\u91cd\u65b0\u751f\u6210!", "data": {"token": "st288dgsh8at026ba0qti0hfbos1gmt3n9"}}
2021-10-19 17:23:41,619 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:23:41] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:23:53,450 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\services\\LoginLogDBS.py', reloading
2021-10-19 17:23:53,511 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:23:54,004 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:23:54,011 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:23:54,046 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:23:54,046 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:24:48,538 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\services\\LoginLogDBS.py', reloading
2021-10-19 17:24:48,595 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:24:49,147 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:24:49,155 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:24:49,193 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:24:49,194 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:24:54,549 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u5931\u6548\u91cd\u65b0\u751f\u6210!", "data": {"token": "3vl442c2plnrl25hpjvb39bbpna1gmt3pi"}}
2021-10-19 17:24:54,550 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:24:54] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:25:13,154 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u5931\u6548\u91cd\u65b0\u751f\u6210!", "data": {"token": "4anbnbrqvhr0f2rktgrrgtp731v1gmt3q4"}}
2021-10-19 17:25:13,155 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:25:13] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:25:49,909 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:25:49,971 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:25:50,459 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:25:50,466 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:25:50,502 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:25:50,502 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:25:51,830 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u5931\u6548\u91cd\u65b0\u751f\u6210!", "data": {"token": "0206co4nckesg26ojoa3v5bctqe1gmt3rb"}}
2021-10-19 17:25:51,831 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:25:51] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:26:02,870 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\services\\LoginLogDBS.py', reloading
2021-10-19 17:26:02,940 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:26:03,440 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:26:03,449 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:26:03,490 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:26:03,490 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:26:03,816 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u672a\u5931\u6548\u76f4\u63a5\u8fd4\u56de!", "data": {}}
2021-10-19 17:26:03,831 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:26:03] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:26:23,056 INFO _internal.py:225  * Detected change in 'E:\\code\\zzg_test_service\\app\\api\\demo.py', reloading
2021-10-19 17:26:23,119 INFO _internal.py:225  * Restarting with stat
2021-10-19 17:26:23,649 WARNING _internal.py:225  * Debugger is active!
2021-10-19 17:26:23,657 INFO _internal.py:225  * Debugger PIN: 222-808-443
2021-10-19 17:26:23,693 WARNING _internal.py:225  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 17:26:23,693 INFO _internal.py:225  * Running on http://10.20.58.93:7890/ (Press CTRL+C to quit)
2021-10-19 17:26:24,337 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u672a\u5931\u6548\u76f4\u63a5\u8fd4\u56de!", "data": "0206co4nckesg26ojoa3v5bctqe1gmt3rb"}
2021-10-19 17:26:24,351 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:26:24] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:26:25,315 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u672a\u5931\u6548\u76f4\u63a5\u8fd4\u56de!", "data": "0206co4nckesg26ojoa3v5bctqe1gmt3rb"}
2021-10-19 17:26:25,329 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:26:25] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:26:26,079 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u672a\u5931\u6548\u76f4\u63a5\u8fd4\u56de!", "data": "0206co4nckesg26ojoa3v5bctqe1gmt3rb"}
2021-10-19 17:26:26,094 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:26:26] "POST /testservice/login HTTP/1.1" 200 -
2021-10-19 17:26:26,951 INFO response_service.py:48 __status:200__headers:{"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Method": "*", "Access-Control-Allow-Headers": "*"}__body:{"code": "0", "message": "\u6210\u529f,token\u672a\u5931\u6548\u76f4\u63a5\u8fd4\u56de!", "data": "0206co4nckesg26ojoa3v5bctqe1gmt3rb"}
2021-10-19 17:26:26,964 INFO _internal.py:225 10.20.58.93 - - [19/Oct/2021 17:26:26] "POST /testservice/login HTTP/1.1" 200 -
